# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kanishk/Downloads/Dev/PythonProjects/audiomix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kanishk/Downloads/Dev/PythonProjects/audiomix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kanishk/Downloads/Dev/PythonProjects/audiomix/CMakeFiles /Users/kanishk/Downloads/Dev/PythonProjects/audiomix//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kanishk/Downloads/Dev/PythonProjects/audiomix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named audiomix

# Build rule for target.
audiomix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 audiomix
.PHONY : audiomix

# fast build rule for target.
audiomix/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/build
.PHONY : audiomix/fast

src/audio_io.o: src/audio_io.cpp.o
.PHONY : src/audio_io.o

# target to build an object file
src/audio_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/audio_io.cpp.o
.PHONY : src/audio_io.cpp.o

src/audio_io.i: src/audio_io.cpp.i
.PHONY : src/audio_io.i

# target to preprocess a source file
src/audio_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/audio_io.cpp.i
.PHONY : src/audio_io.cpp.i

src/audio_io.s: src/audio_io.cpp.s
.PHONY : src/audio_io.s

# target to generate assembly for a file
src/audio_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/audio_io.cpp.s
.PHONY : src/audio_io.cpp.s

src/channel.o: src/channel.cpp.o
.PHONY : src/channel.o

# target to build an object file
src/channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/channel.cpp.o
.PHONY : src/channel.cpp.o

src/channel.i: src/channel.cpp.i
.PHONY : src/channel.i

# target to preprocess a source file
src/channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/channel.cpp.i
.PHONY : src/channel.cpp.i

src/channel.s: src/channel.cpp.s
.PHONY : src/channel.s

# target to generate assembly for a file
src/channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/channel.cpp.s
.PHONY : src/channel.cpp.s

src/feedback_detector.o: src/feedback_detector.cpp.o
.PHONY : src/feedback_detector.o

# target to build an object file
src/feedback_detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/feedback_detector.cpp.o
.PHONY : src/feedback_detector.cpp.o

src/feedback_detector.i: src/feedback_detector.cpp.i
.PHONY : src/feedback_detector.i

# target to preprocess a source file
src/feedback_detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/feedback_detector.cpp.i
.PHONY : src/feedback_detector.cpp.i

src/feedback_detector.s: src/feedback_detector.cpp.s
.PHONY : src/feedback_detector.s

# target to generate assembly for a file
src/feedback_detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/feedback_detector.cpp.s
.PHONY : src/feedback_detector.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mixer.o: src/mixer.cpp.o
.PHONY : src/mixer.o

# target to build an object file
src/mixer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/mixer.cpp.o
.PHONY : src/mixer.cpp.o

src/mixer.i: src/mixer.cpp.i
.PHONY : src/mixer.i

# target to preprocess a source file
src/mixer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/mixer.cpp.i
.PHONY : src/mixer.cpp.i

src/mixer.s: src/mixer.cpp.s
.PHONY : src/mixer.s

# target to generate assembly for a file
src/mixer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/mixer.cpp.s
.PHONY : src/mixer.cpp.s

src/notch_filter.o: src/notch_filter.cpp.o
.PHONY : src/notch_filter.o

# target to build an object file
src/notch_filter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/notch_filter.cpp.o
.PHONY : src/notch_filter.cpp.o

src/notch_filter.i: src/notch_filter.cpp.i
.PHONY : src/notch_filter.i

# target to preprocess a source file
src/notch_filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/notch_filter.cpp.i
.PHONY : src/notch_filter.cpp.i

src/notch_filter.s: src/notch_filter.cpp.s
.PHONY : src/notch_filter.s

# target to generate assembly for a file
src/notch_filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/audiomix.dir/build.make CMakeFiles/audiomix.dir/src/notch_filter.cpp.s
.PHONY : src/notch_filter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... audiomix"
	@echo "... src/audio_io.o"
	@echo "... src/audio_io.i"
	@echo "... src/audio_io.s"
	@echo "... src/channel.o"
	@echo "... src/channel.i"
	@echo "... src/channel.s"
	@echo "... src/feedback_detector.o"
	@echo "... src/feedback_detector.i"
	@echo "... src/feedback_detector.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mixer.o"
	@echo "... src/mixer.i"
	@echo "... src/mixer.s"
	@echo "... src/notch_filter.o"
	@echo "... src/notch_filter.i"
	@echo "... src/notch_filter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

